### ISSUE TITLE
add woocommerce rules

### ISSUE THREAD

**Issue by aelsharawi** [razvanstanga/varnish-caching-wordpress-plugin#1]
Hello

since woocommerce is pretty common plugin, why not include its default vcl?

**Comment by razvanstanga** [comment]
I will do it at some point when I have free time. Feel free to do it yourself and submit it to me to add it to VCaching.

**Comment by aelsharawi** [comment]
https://pastebin.com/SfUDXthY

have a look on the above one
-although Im not getting a high HIT

one of the plugins sets this cookie
`Set-Cookie:	learn_press_user_guest_id=1494238568; expires=Mon, 08-May-2017 12:16:08 GMT; Max-Age=7200; path=/
Expires:	Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control:	no-store, no-cache, must-revalidate
Pragma:	no-cache
X-VC-Enabled:	true
X-VC-TTL:	1600
X-VC-Debug:	true`


I tried to make hash for it as u see on the vcl, but I think there is a better idea, as it is not working too

**Comment by aelsharawi** [comment]
most of the time also it shows the logged in cookie of the plugin, although I removed it from the vcl and the plugin setting

**Comment by aelsharawi** [comment]
`<!-- Performance optimized by W3 Total Cache. Learn more: https://www.w3-edge.com/products/

Page Caching using memcached
Page cache debug info:
Engine:             memcached
Cache key:          87640d8ef8ada62502f6c56c6c045063_ssl
Creation Time:      1494242386.000s
Header info:
Expires:             Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control:       no-store, no-cache, must-revalidate
Pragma:              no-cache
Content-Type:        text/html; charset=UTF-8
X-VC-Enabled:        true
X-VC-TTL:            1600
X-VC-Debug:          true
Set-Cookie:          wordpress_logged_in_084e0343a0486ff05530df6c705c8bb4=29a0d67e52602a1391fe79a749cb6bb8; expires=Mon, 08-May-2017 12:19:45 GMT; Max-Age=3600
Link:                <https://domain/wp-json/>; rel="https://api.w.org/"
Link:                <https://domain/?p=8280>; rel=shortlink
Db cache debug info:
Engine:             redis
Total queries:      149
Cached queries:     62
Total query time:   0.3270
`
