### ISSUE TITLE
Is Vcaching generating PHP sessions?

### ISSUE THREAD

**Issue by ahmed-sigmalux** [razvanstanga/varnish-caching-wordpress-plugin#8]
I was looking through the vcaching code and noticed the following entry:

`/var/www/wordpress/wp-content/plugins/vcaching/vcaching.php:105:                session_start();`

What's the purpose of this PHP session and does it negatively impact downstream caching?

**Comment by razvanstanga** [comment]
Is using php sessions only on the backend side (wp-admin).

**Comment by ahmed-sigmalux** [comment]
OK, thanks for the clarification. I have a plugin generating PHP sessions on all pages so I'm trying to identify the culprit.
